/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as KiskoRouteImport } from './routes/kisko'
import { Route as PilgrimRouteImport } from './routes/pilgrim'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAlertsIndexRouteImport } from './routes/admin/alerts/index'
import { Route as AdminAlertsCreateRouteImport } from './routes/admin/alerts/create'
import { Route as AdminAuditIndexRouteImport } from './routes/admin/audit/index'
import { Route as AdminCrowdIndexRouteImport } from './routes/admin/crowd/index'
import { Route as AdminCrowdZoneIdRouteImport } from './routes/admin/crowd/$zoneId'
import { Route as AdminEventsIndexRouteImport } from './routes/admin/events/index'
import { Route as AdminEventsEventIdRouteImport } from './routes/admin/events/$eventId'
import { Route as AdminFacilitiesIndexRouteImport } from './routes/admin/facilities/index'
import { Route as AdminFacilitiesFacilityIdRouteImport } from './routes/admin/facilities/$facilityId'
import { Route as AdminFoodIndexRouteImport } from './routes/admin/food/index'
import { Route as AdminFoodKitchenIdRouteImport } from './routes/admin/food/$kitchenId'
import { Route as AdminFoodShortagesRouteImport } from './routes/admin/food/shortages'
import { Route as AdminGuidanceIndexRouteImport } from './routes/admin/guidance/index'
import { Route as AdminParkingIndexRouteImport } from './routes/admin/parking/index'
import { Route as AdminParkingParkingIdRouteImport } from './routes/admin/parking/$parkingId'
import { Route as AdminPlacesIndexRouteImport } from './routes/admin/places/index'
import { Route as AdminPlacesPlaceIdRouteImport } from './routes/admin/places/$placeId'
import { Route as AdminReportsIndexRouteImport } from './routes/admin/reports/index'
import { Route as AdminRoutesIndexRouteImport } from './routes/admin/routes/index'
import { Route as AdminRoutesRouteIdRouteImport } from './routes/admin/routes/$routeId'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminVolunteersIndexRouteImport } from './routes/admin/volunteers/index'
import { Route as AdminVolunteersVolunteerIdRouteImport } from './routes/admin/volunteers/$volunteerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const KiskoRoute = KiskoRouteImport.update({
  id: '/kisko',
  path: '/kisko',
  getParentRoute: () => rootRouteImport,
} as any)
const PilgrimRoute = PilgrimRouteImport.update({
  id: '/pilgrim',
  path: '/pilgrim',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlertsIndexRoute = AdminAlertsIndexRouteImport.update({
  id: '/alerts/',
  path: '/alerts/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlertsCreateRoute = AdminAlertsCreateRouteImport.update({
  id: '/alerts/create',
  path: '/alerts/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditIndexRoute = AdminAuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCrowdIndexRoute = AdminCrowdIndexRouteImport.update({
  id: '/crowd/',
  path: '/crowd/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCrowdZoneIdRoute = AdminCrowdZoneIdRouteImport.update({
  id: '/crowd/$zoneId',
  path: '/crowd/$zoneId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsIndexRoute = AdminEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsEventIdRoute = AdminEventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFacilitiesIndexRoute = AdminFacilitiesIndexRouteImport.update({
  id: '/facilities/',
  path: '/facilities/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFacilitiesFacilityIdRoute =
  AdminFacilitiesFacilityIdRouteImport.update({
    id: '/facilities/$facilityId',
    path: '/facilities/$facilityId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminFoodIndexRoute = AdminFoodIndexRouteImport.update({
  id: '/food/',
  path: '/food/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFoodKitchenIdRoute = AdminFoodKitchenIdRouteImport.update({
  id: '/food/$kitchenId',
  path: '/food/$kitchenId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFoodShortagesRoute = AdminFoodShortagesRouteImport.update({
  id: '/food/shortages',
  path: '/food/shortages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGuidanceIndexRoute = AdminGuidanceIndexRouteImport.update({
  id: '/guidance/',
  path: '/guidance/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminParkingIndexRoute = AdminParkingIndexRouteImport.update({
  id: '/parking/',
  path: '/parking/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminParkingParkingIdRoute = AdminParkingParkingIdRouteImport.update({
  id: '/parking/$parkingId',
  path: '/parking/$parkingId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlacesIndexRoute = AdminPlacesIndexRouteImport.update({
  id: '/places/',
  path: '/places/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlacesPlaceIdRoute = AdminPlacesPlaceIdRouteImport.update({
  id: '/places/$placeId',
  path: '/places/$placeId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsIndexRoute = AdminReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRoutesIndexRoute = AdminRoutesIndexRouteImport.update({
  id: '/routes/',
  path: '/routes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRoutesRouteIdRoute = AdminRoutesRouteIdRouteImport.update({
  id: '/routes/$routeId',
  path: '/routes/$routeId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVolunteersIndexRoute = AdminVolunteersIndexRouteImport.update({
  id: '/volunteers/',
  path: '/volunteers/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVolunteersVolunteerIdRoute =
  AdminVolunteersVolunteerIdRouteImport.update({
    id: '/volunteers/$volunteerId',
    path: '/volunteers/$volunteerId',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/kisko': typeof KiskoRoute
  '/pilgrim': typeof PilgrimRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/alerts/create': typeof AdminAlertsCreateRoute
  '/admin/crowd/$zoneId': typeof AdminCrowdZoneIdRoute
  '/admin/events/$eventId': typeof AdminEventsEventIdRoute
  '/admin/facilities/$facilityId': typeof AdminFacilitiesFacilityIdRoute
  '/admin/food/$kitchenId': typeof AdminFoodKitchenIdRoute
  '/admin/food/shortages': typeof AdminFoodShortagesRoute
  '/admin/parking/$parkingId': typeof AdminParkingParkingIdRoute
  '/admin/places/$placeId': typeof AdminPlacesPlaceIdRoute
  '/admin/routes/$routeId': typeof AdminRoutesRouteIdRoute
  '/admin/volunteers/$volunteerId': typeof AdminVolunteersVolunteerIdRoute
  '/admin/alerts/': typeof AdminAlertsIndexRoute
  '/admin/audit/': typeof AdminAuditIndexRoute
  '/admin/crowd/': typeof AdminCrowdIndexRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/admin/facilities/': typeof AdminFacilitiesIndexRoute
  '/admin/food/': typeof AdminFoodIndexRoute
  '/admin/guidance/': typeof AdminGuidanceIndexRoute
  '/admin/parking/': typeof AdminParkingIndexRoute
  '/admin/places/': typeof AdminPlacesIndexRoute
  '/admin/reports/': typeof AdminReportsIndexRoute
  '/admin/routes/': typeof AdminRoutesIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/volunteers/': typeof AdminVolunteersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kisko': typeof KiskoRoute
  '/pilgrim': typeof PilgrimRoute
  '/admin': typeof AdminIndexRoute
  '/admin/alerts/create': typeof AdminAlertsCreateRoute
  '/admin/crowd/$zoneId': typeof AdminCrowdZoneIdRoute
  '/admin/events/$eventId': typeof AdminEventsEventIdRoute
  '/admin/facilities/$facilityId': typeof AdminFacilitiesFacilityIdRoute
  '/admin/food/$kitchenId': typeof AdminFoodKitchenIdRoute
  '/admin/food/shortages': typeof AdminFoodShortagesRoute
  '/admin/parking/$parkingId': typeof AdminParkingParkingIdRoute
  '/admin/places/$placeId': typeof AdminPlacesPlaceIdRoute
  '/admin/routes/$routeId': typeof AdminRoutesRouteIdRoute
  '/admin/volunteers/$volunteerId': typeof AdminVolunteersVolunteerIdRoute
  '/admin/alerts': typeof AdminAlertsIndexRoute
  '/admin/audit': typeof AdminAuditIndexRoute
  '/admin/crowd': typeof AdminCrowdIndexRoute
  '/admin/events': typeof AdminEventsIndexRoute
  '/admin/facilities': typeof AdminFacilitiesIndexRoute
  '/admin/food': typeof AdminFoodIndexRoute
  '/admin/guidance': typeof AdminGuidanceIndexRoute
  '/admin/parking': typeof AdminParkingIndexRoute
  '/admin/places': typeof AdminPlacesIndexRoute
  '/admin/reports': typeof AdminReportsIndexRoute
  '/admin/routes': typeof AdminRoutesIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/volunteers': typeof AdminVolunteersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/kisko': typeof KiskoRoute
  '/pilgrim': typeof PilgrimRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/alerts/create': typeof AdminAlertsCreateRoute
  '/admin/crowd/$zoneId': typeof AdminCrowdZoneIdRoute
  '/admin/events/$eventId': typeof AdminEventsEventIdRoute
  '/admin/facilities/$facilityId': typeof AdminFacilitiesFacilityIdRoute
  '/admin/food/$kitchenId': typeof AdminFoodKitchenIdRoute
  '/admin/food/shortages': typeof AdminFoodShortagesRoute
  '/admin/parking/$parkingId': typeof AdminParkingParkingIdRoute
  '/admin/places/$placeId': typeof AdminPlacesPlaceIdRoute
  '/admin/routes/$routeId': typeof AdminRoutesRouteIdRoute
  '/admin/volunteers/$volunteerId': typeof AdminVolunteersVolunteerIdRoute
  '/admin/alerts/': typeof AdminAlertsIndexRoute
  '/admin/audit/': typeof AdminAuditIndexRoute
  '/admin/crowd/': typeof AdminCrowdIndexRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/admin/facilities/': typeof AdminFacilitiesIndexRoute
  '/admin/food/': typeof AdminFoodIndexRoute
  '/admin/guidance/': typeof AdminGuidanceIndexRoute
  '/admin/parking/': typeof AdminParkingIndexRoute
  '/admin/places/': typeof AdminPlacesIndexRoute
  '/admin/reports/': typeof AdminReportsIndexRoute
  '/admin/routes/': typeof AdminRoutesIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/volunteers/': typeof AdminVolunteersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/kisko'
    | '/pilgrim'
    | '/admin/'
    | '/admin/alerts/create'
    | '/admin/crowd/$zoneId'
    | '/admin/events/$eventId'
    | '/admin/facilities/$facilityId'
    | '/admin/food/$kitchenId'
    | '/admin/food/shortages'
    | '/admin/parking/$parkingId'
    | '/admin/places/$placeId'
    | '/admin/routes/$routeId'
    | '/admin/volunteers/$volunteerId'
    | '/admin/alerts/'
    | '/admin/audit/'
    | '/admin/crowd/'
    | '/admin/events/'
    | '/admin/facilities/'
    | '/admin/food/'
    | '/admin/guidance/'
    | '/admin/parking/'
    | '/admin/places/'
    | '/admin/reports/'
    | '/admin/routes/'
    | '/admin/settings/'
    | '/admin/users/'
    | '/admin/volunteers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kisko'
    | '/pilgrim'
    | '/admin'
    | '/admin/alerts/create'
    | '/admin/crowd/$zoneId'
    | '/admin/events/$eventId'
    | '/admin/facilities/$facilityId'
    | '/admin/food/$kitchenId'
    | '/admin/food/shortages'
    | '/admin/parking/$parkingId'
    | '/admin/places/$placeId'
    | '/admin/routes/$routeId'
    | '/admin/volunteers/$volunteerId'
    | '/admin/alerts'
    | '/admin/audit'
    | '/admin/crowd'
    | '/admin/events'
    | '/admin/facilities'
    | '/admin/food'
    | '/admin/guidance'
    | '/admin/parking'
    | '/admin/places'
    | '/admin/reports'
    | '/admin/routes'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/volunteers'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/kisko'
    | '/pilgrim'
    | '/admin/'
    | '/admin/alerts/create'
    | '/admin/crowd/$zoneId'
    | '/admin/events/$eventId'
    | '/admin/facilities/$facilityId'
    | '/admin/food/$kitchenId'
    | '/admin/food/shortages'
    | '/admin/parking/$parkingId'
    | '/admin/places/$placeId'
    | '/admin/routes/$routeId'
    | '/admin/volunteers/$volunteerId'
    | '/admin/alerts/'
    | '/admin/audit/'
    | '/admin/crowd/'
    | '/admin/events/'
    | '/admin/facilities/'
    | '/admin/food/'
    | '/admin/guidance/'
    | '/admin/parking/'
    | '/admin/places/'
    | '/admin/reports/'
    | '/admin/routes/'
    | '/admin/settings/'
    | '/admin/users/'
    | '/admin/volunteers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  KiskoRoute: typeof KiskoRoute
  PilgrimRoute: typeof PilgrimRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kisko': {
      id: '/kisko'
      path: '/kisko'
      fullPath: '/kisko'
      preLoaderRoute: typeof KiskoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilgrim': {
      id: '/pilgrim'
      path: '/pilgrim'
      fullPath: '/pilgrim'
      preLoaderRoute: typeof PilgrimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alerts/': {
      id: '/admin/alerts/'
      path: '/alerts'
      fullPath: '/admin/alerts/'
      preLoaderRoute: typeof AdminAlertsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alerts/create': {
      id: '/admin/alerts/create'
      path: '/alerts/create'
      fullPath: '/admin/alerts/create'
      preLoaderRoute: typeof AdminAlertsCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit/': {
      id: '/admin/audit/'
      path: '/audit'
      fullPath: '/admin/audit/'
      preLoaderRoute: typeof AdminAuditIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/crowd/': {
      id: '/admin/crowd/'
      path: '/crowd'
      fullPath: '/admin/crowd/'
      preLoaderRoute: typeof AdminCrowdIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/crowd/$zoneId': {
      id: '/admin/crowd/$zoneId'
      path: '/crowd/$zoneId'
      fullPath: '/admin/crowd/$zoneId'
      preLoaderRoute: typeof AdminCrowdZoneIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/': {
      id: '/admin/events/'
      path: '/events'
      fullPath: '/admin/events/'
      preLoaderRoute: typeof AdminEventsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/$eventId': {
      id: '/admin/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/admin/events/$eventId'
      preLoaderRoute: typeof AdminEventsEventIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/facilities/': {
      id: '/admin/facilities/'
      path: '/facilities'
      fullPath: '/admin/facilities/'
      preLoaderRoute: typeof AdminFacilitiesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/facilities/$facilityId': {
      id: '/admin/facilities/$facilityId'
      path: '/facilities/$facilityId'
      fullPath: '/admin/facilities/$facilityId'
      preLoaderRoute: typeof AdminFacilitiesFacilityIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/food/': {
      id: '/admin/food/'
      path: '/food'
      fullPath: '/admin/food/'
      preLoaderRoute: typeof AdminFoodIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/food/$kitchenId': {
      id: '/admin/food/$kitchenId'
      path: '/food/$kitchenId'
      fullPath: '/admin/food/$kitchenId'
      preLoaderRoute: typeof AdminFoodKitchenIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/food/shortages': {
      id: '/admin/food/shortages'
      path: '/food/shortages'
      fullPath: '/admin/food/shortages'
      preLoaderRoute: typeof AdminFoodShortagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/guidance/': {
      id: '/admin/guidance/'
      path: '/guidance'
      fullPath: '/admin/guidance/'
      preLoaderRoute: typeof AdminGuidanceIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/parking/': {
      id: '/admin/parking/'
      path: '/parking'
      fullPath: '/admin/parking/'
      preLoaderRoute: typeof AdminParkingIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/parking/$parkingId': {
      id: '/admin/parking/$parkingId'
      path: '/parking/$parkingId'
      fullPath: '/admin/parking/$parkingId'
      preLoaderRoute: typeof AdminParkingParkingIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/places/': {
      id: '/admin/places/'
      path: '/places'
      fullPath: '/admin/places/'
      preLoaderRoute: typeof AdminPlacesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/places/$placeId': {
      id: '/admin/places/$placeId'
      path: '/places/$placeId'
      fullPath: '/admin/places/$placeId'
      preLoaderRoute: typeof AdminPlacesPlaceIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports/': {
      id: '/admin/reports/'
      path: '/reports'
      fullPath: '/admin/reports/'
      preLoaderRoute: typeof AdminReportsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/routes/': {
      id: '/admin/routes/'
      path: '/routes'
      fullPath: '/admin/routes/'
      preLoaderRoute: typeof AdminRoutesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/routes/$routeId': {
      id: '/admin/routes/$routeId'
      path: '/routes/$routeId'
      fullPath: '/admin/routes/$routeId'
      preLoaderRoute: typeof AdminRoutesRouteIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/volunteers/': {
      id: '/admin/volunteers/'
      path: '/volunteers'
      fullPath: '/admin/volunteers/'
      preLoaderRoute: typeof AdminVolunteersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/volunteers/$volunteerId': {
      id: '/admin/volunteers/$volunteerId'
      path: '/volunteers/$volunteerId'
      fullPath: '/admin/volunteers/$volunteerId'
      preLoaderRoute: typeof AdminVolunteersVolunteerIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAlertsCreateRoute: typeof AdminAlertsCreateRoute
  AdminCrowdZoneIdRoute: typeof AdminCrowdZoneIdRoute
  AdminEventsEventIdRoute: typeof AdminEventsEventIdRoute
  AdminFacilitiesFacilityIdRoute: typeof AdminFacilitiesFacilityIdRoute
  AdminFoodKitchenIdRoute: typeof AdminFoodKitchenIdRoute
  AdminFoodShortagesRoute: typeof AdminFoodShortagesRoute
  AdminParkingParkingIdRoute: typeof AdminParkingParkingIdRoute
  AdminPlacesPlaceIdRoute: typeof AdminPlacesPlaceIdRoute
  AdminRoutesRouteIdRoute: typeof AdminRoutesRouteIdRoute
  AdminVolunteersVolunteerIdRoute: typeof AdminVolunteersVolunteerIdRoute
  AdminAlertsIndexRoute: typeof AdminAlertsIndexRoute
  AdminAuditIndexRoute: typeof AdminAuditIndexRoute
  AdminCrowdIndexRoute: typeof AdminCrowdIndexRoute
  AdminEventsIndexRoute: typeof AdminEventsIndexRoute
  AdminFacilitiesIndexRoute: typeof AdminFacilitiesIndexRoute
  AdminFoodIndexRoute: typeof AdminFoodIndexRoute
  AdminGuidanceIndexRoute: typeof AdminGuidanceIndexRoute
  AdminParkingIndexRoute: typeof AdminParkingIndexRoute
  AdminPlacesIndexRoute: typeof AdminPlacesIndexRoute
  AdminReportsIndexRoute: typeof AdminReportsIndexRoute
  AdminRoutesIndexRoute: typeof AdminRoutesIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminVolunteersIndexRoute: typeof AdminVolunteersIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminAlertsCreateRoute: AdminAlertsCreateRoute,
  AdminCrowdZoneIdRoute: AdminCrowdZoneIdRoute,
  AdminEventsEventIdRoute: AdminEventsEventIdRoute,
  AdminFacilitiesFacilityIdRoute: AdminFacilitiesFacilityIdRoute,
  AdminFoodKitchenIdRoute: AdminFoodKitchenIdRoute,
  AdminFoodShortagesRoute: AdminFoodShortagesRoute,
  AdminParkingParkingIdRoute: AdminParkingParkingIdRoute,
  AdminPlacesPlaceIdRoute: AdminPlacesPlaceIdRoute,
  AdminRoutesRouteIdRoute: AdminRoutesRouteIdRoute,
  AdminVolunteersVolunteerIdRoute: AdminVolunteersVolunteerIdRoute,
  AdminAlertsIndexRoute: AdminAlertsIndexRoute,
  AdminAuditIndexRoute: AdminAuditIndexRoute,
  AdminCrowdIndexRoute: AdminCrowdIndexRoute,
  AdminEventsIndexRoute: AdminEventsIndexRoute,
  AdminFacilitiesIndexRoute: AdminFacilitiesIndexRoute,
  AdminFoodIndexRoute: AdminFoodIndexRoute,
  AdminGuidanceIndexRoute: AdminGuidanceIndexRoute,
  AdminParkingIndexRoute: AdminParkingIndexRoute,
  AdminPlacesIndexRoute: AdminPlacesIndexRoute,
  AdminReportsIndexRoute: AdminReportsIndexRoute,
  AdminRoutesIndexRoute: AdminRoutesIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminVolunteersIndexRoute: AdminVolunteersIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  KiskoRoute: KiskoRoute,
  PilgrimRoute: PilgrimRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
